// Generated by Synactive Designer Version 2, 11, 208, 0
// Description:Edited by TE
if(_transaction == 'XD01') {
	pushbutton([TOOLBAR],"@2M@Back",'/n');
	onUIEvents['/3'] = {'fcode':'/n'};
	onUIEvents['/12'] = {'fcode':'/n'};
	onUIEvents['/15'] = {'fcode':'/n'};
}